using System.ComponentModel.DataAnnotations;

namespace WebMkt.Models
{
    public class Post
    {
        public int Id { get; set; }

        [Required, MaxLength(255)]
        public string Title { get; set; }

        [Required, MaxLength(255)]
        public string Slug { get; set; }

        public string? ThumbnailUrl { get; set; }

        public string? Description { get; set; }

        [Required]
        public string Content { get; set; }

        [MaxLength(255)]
        public string? MetaTitle { get; set; }

        [MaxLength(500)]
        public string? MetaDescription { get; set; }

        public string? MetaKeywords { get; set; }

        [MaxLength(1000)]
        public string? SchemaMarkup { get; set; } // Schema Markup JSON generated by AI

        public DateTime CreatedAt { get; set; } = DateTime.Now;

        public DateTime? UpdatedAt { get; set; }

        public bool IsPublished { get; set; } = false;

        public int CategoryId { get; set; }
        public Category Category { get; set; }

        public ICollection<PostTag> PostTags { get; set; } = new List<PostTag>();
    }
}
